const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',


    ///admin
    // FETCH_COMPANY_SIZE_FAILED: 'FETCH_COMPANY_SIZE_FAILED',
    // FETCH_COMPANY_SIZE_SUCCESS: 'FETCH_COMPANY_SIZE_SUCCESS',
    // FETCH_COMPANY_SIZE_START: 'FETCH_COMPANY_SIZE_START',

    // FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    // FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    // FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    // FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',

    FETCH_ALLCODES_START: 'FETCH_ALLCODES_START',
    FETCH_ALLCODES_SUCCESS: 'FETCH_ALLCODES_SUCCESS',
    FETCH_ALLCODES_FAILED: 'FETCH_ALLCODES_FAILED',
})

export default actionTypes;