const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',


    ///admin
    FETCH_ALLCODES_START: 'FETCH_ALLCODES_START',
    FETCH_ALLCODES_SUCCESS: 'FETCH_ALLCODES_SUCCESS',
    FETCH_ALLCODES_FAILED: 'FETCH_ALLCODES_FAILED',

    CREATE_COMPANY_SUCCESS: 'CREATE_COMPANY_SUCCESS',
    CREATE_COMPANY_FAILED: 'CREATE_COMPANY_FAILED',


    //home page
    FETCH_TOP_COMPANY_SUCCESS: 'FETCH_TOP_COMPANY_SUCCESS',
    FETCH_TOP_COMPANY_FAILED: 'FETCH_TOP_COMPANY_FAILED'
})

export default actionTypes;